syntax = "All"
# Used for line-wrapping
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
# Whether parentheses should be applied on function calls with a single
# string/table argument.
call_parentheses = "Always"
space_after_function_names = "Never"
collapse_simple_statement = "Never"
